### ISSUE TITLE
Add Audioservice Duden

### ISSUE THREAD

**Issue by MarcoSchicke** [AwesomeTTS/AwesomeTTS#95]
Duden is the "German Oxford".
For each word is also an Audiolink. 
(The small speaker symbol below from Aussprache).

In the description this Plugin for Anki supports it already, but I don't want to leave Awesome TTS :)
https://ankiweb.net/shared/info/3100585138

**Comment by corpulentcoffee** [comment]
Thanks for the suggestion! I haven't looked at the Duden site yet, but I think that I should be able to add this to AwesomeTTS.

**Comment by corpulentcoffee** [comment]
I have started to look at Duden. I wonder about the best approach though...

Download Audio seems to convert letters with diacritics (e.g. **ü** to **ue**), then ask for `http://www.duden.de/rechtschreibung/<converted>`, and then search that for audio links... in my rough testing, this works for some words but not others... for example, **über** would be http://www.duden.de/rechtschreibung/ueber but there is no page there... the page is actually at http://www.duden.de/rechtschreibung/ueber_auf_darueber_darauf where there is indeed an audio link.

I think a more robust solution might be to do a search (e.g. http://www.duden.de/suchen/dudenonline?s=%C3%BCber for über), and then go through all of the returned pages looking for audio... this will be slower... and I think this *could* return the incorrect audio... for example, if the user enters "Wörter" (words), AwesomeTTS would retrieve http://www.duden.de/suchen/dudenonline?s=w%C3%B6rter then go to http://www.duden.de/rechtschreibung/Woerter where it would find no audio link and then go to http://www.duden.de/rechtschreibung/Woerterbuch where it *would* find an audio link, returning the incorrect audio (Wörterbuch instead of Wörter)... I am not sure how to automatically verify that a particular page is the "correct" for what the user entered originally... I *think* I can cross-check the "Betonung" line on the resulting dictionary page to make sure it matched what the user entered, but I think we need to test it thoroughly.

Is there anything I am missing that would make this easier for AwesomeTTS to pick out the audio links automatically?

Also, if I put this in, are you able to help test it?

**Comment by ChristianKleineidam** [comment]
Besides the diacritics there's also "ß" that Duden internally translates as "sz".

Strategy proposal:
Go to http://www.duden.de/suchen/dudenonline?s=%search-term% .
Interpret the resulting link as http://www.duden.de/rechtschreibung/%duden-term% .
Split %duden-term% based on "_" and load the first string into %head-duden-term%.
Have a function asci() that transforms ä, ö, ü and ß into ae, oe, ue and sz.
Check whether asci(%search-term%)==%head-duden-term%. If so, go to http://www.duden.de/rechtschreibung/%duden-term% and grab the audio.

**Comment by corpulentcoffee** [comment]
> Go to http://www.duden.de/suchen/dudenonline?s=%search-term% .
> Interpret the resulting link as http://www.duden.de/rechtschreibung/%duden-term% .
> Split %duden-term% based on "_" and load the first string into %head-duden-term%.
> Have a function asci() that transforms ä, ö, ü and ß into ae, oe, ue and sz.
> Check whether asci(%search-term%)==%head-duden-term%. If so, go to > http://www.duden.de/rechtschreibung/%duden-term% and grab the audio.


@ChristianKleineidam -- Thanks, I think your strategy to split on the underscore, compare it back to the original input, and follow it if it matches might work -- I wonder if I should write it to follow multiple links or if I'll usually get it in the first one -- I also wonder if I should normalize case or drop any other characters (like [in Howjsay](https://github.com/AwesomeTTS/AwesomeTTS/blob/develop/addon/awesometts/service/howjsay.py#L73)). (It seems like Duden correctly represents German nouns capitalized in URLs, but it probably doesn't matter to be case-sensitive?)

Regardless, I'll try to run this over a large German shared deck to make sure it works.

> "ß" that Duden internally translates as "sz"

This bit is interesting -- when I learned German many years ago, I was taught to type `ß` as `ss` if I was typing somewhere where I could not type the Eszett -- I think I will do a special mapping specifically for Duden, as [the existing ASCII mapper I have](https://github.com/AwesomeTTS/AwesomeTTS/blob/develop/addon/awesometts/service/base.py#L100) won't do what I want here (which maps `ß` as `ss` instead of `sz`, and maps the umlauted vowels without the `e`, as originally I wrote that for an English dictionary for words like "döppleganger").

Thanks, all, I'll look at this soon -- maybe this weekend.

**Comment by ChristianKleineidam** [comment]
>It seems like Duden correctly represents German nouns capitalized in URLs, but it probably doesn't matter to be case-sensitive?

I posted a question to the German stackexchange to check: http://german.stackexchange.com/questions/29099/are-there-german-words-that-get-pronounced-differently-based-on-whether-they-are

**Comment by uklauer** [comment]
Note that there also are _homonyms_, words that are spelt and capitalized the same but still pronounced differently. Well-known examples are _umfahren_ (stress on first or second syllable) and _Montage_ [ˈmoːntagə]/[mɔnˈtaːʒə]. They usually have separate Duden pages.

**Comment by corpulentcoffee** [comment]
Does anyone happen to know if Duden has any audio for any multi-word *phrases* (i.e. with spaces), or can we limit support here for single words only that contain no spaces?

**Comment by corpulentcoffee** [comment]
I've done a first attempt at the Duden service.

The rules around the underscore need to be refined *and* I coincidentally stumbled upon a multi-word recording pretty quickly, but I don't know how realistic it is that people will want such recordings (e.g. when I use an input of "Tag", AwesomeTTS will try http://www.duden.de/rechtschreibung/Tag_ and find nothing there, then try http://www.duden.de/rechtschreibung/Tag_Cloud and find http://www.duden.de/_media_/audio/ID4428241_430791246.mp3, which is incorrect... we probably want it to find http://www.duden.de/rechtschreibung/Tag_Zeit_Zeiteinheit instead... this might be able to be alleviated somewhat by making it only sort by a match rank and not including the URL in the sorting).

**Comment by ChristianKleineidam** [comment]
Maybe you say that either `asci(%search-term%)==%head-duden-term%` or `asci(%search-term%)==underslashTospaces(%duden-term%)` where underslashTospaces turn `_` into ` ` to allow for phrases spanning multiple words?

**Comment by ChristianKleineidam** [comment]
I just revisited a few German-English cards I did a long-time ago. 
A lot of them use articles. 
I have a card that says "der Darm". At present that wouldn't work with the Duden service. I think it would be reasonable to strip the article in a multiword term before sending the queries.
