### ISSUE TITLE
Caching data for <tts> requests

### ISSUE THREAD

**Issue by ChristianKleineidam** [AwesomeTTS/AwesomeTTS#98]
I think it would be great if AwesomeTTS would automatically save the data of a <tts>-request to collection.media. That allows Anki to still have the data when the service goes down. At the present if a Service would go down for an hour AwesomeTTS would throw error messages. Even at cases where a server has 1 second lag it would be highly useful to have a cached version of the data.

**Comment by ChristianKleineidam** [comment]
I just went through the menu and it seems AwesomeTTS already does caching. It's awesome ;)

**Comment by corpulentcoffee** [comment]
Yes, indeed is already does cache successful `<tts>` requests (although, it saves these files locally to `Documents\Anki\addons\awesometts\.cache` rather than your collection's media files so that the cache does not slow down synchronization).

If you like this feature and don't mind it using extra hard drive space, you can increase the default from 70 days to something higher, and you'll have more MP3s locally cached.
